on: push

jobs:
  crx:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: trektor
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: trektor/yarn.lock
      - run: yarn install
        working-directory: trektor
      - uses: browser-actions/setup-chrome@latest
      - run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          chrome --pack-extension=trektor
      - uses: "softprops/action-gh-release@v1"
        with:
          files: "trektor.crx"
