on: push

jobs:
  crx:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: trektor
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: trektor/yarn.lock
      - run: yarn install
        working-directory: trektor
      - uses: browser-actions/setup-chrome@latest
      - run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 1
          echo -n "${CHROME_EXTENSION_KEY}" > trektor.pem
          chrome --pack-extension=trektor --pack-extension-key=trektor.pem
        env:
          CHROME_EXTENSION_KEY: ${{ secrets.CHROME_EXTENSION_KEY }}
      - uses: "softprops/action-gh-release@v1"
        with:
          files: "trektor.crx"

  pages:
    runs-on: ubuntu-latest
    needs: [crx]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          curl -LOf "https://github.com/aboutsource/trektor/releases/download/${GITHUB_REF##*/}/trektor.crx"
          cat > update.xml <<EOF
          <gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
            <app appid="lffnocdloekhnmiadpgfgknfbhgnppgl">
              <updatecheck codebase="https://aboutsource.github.io/trektor/trektor.crx" version="${GITHUB_REF##*/}"/>
            </app>
          </gupdate>
          EOF
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "release ${GITHUB_REF##*/}"
          git push
